// Generated by CoffeeScript 1.3.1
(function() {
  var addMarkerClickHandler, addMarkerToMap, animateMarkers, getCheckboxDivHtml, init, laMarker, map, nyMarker;

  nyMarker = null;

  laMarker = null;

  map = null;

  getCheckboxDivHtml = function() {
    return ['<div id="checboxDiv">', '<input type="checkbox" id="ny" checked>New York', '<input type="checkbox" id="la">Los Angeles', '</div>'].join("");
  };

  addMarkerToMap = function(lat, lng, opacity) {
    var marker;
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      map: map,
      opacity: opacity,
      opacities: []
    });
    return marker;
  };

  addMarkerClickHandler = function(checkbox, marker) {
    return checkbox.click(function() {
      if ($(this).is(":checked")) {
        return marker.opacities = marker.opacities.concat([.2, .4, .6, .8, 1]);
      } else {
        return marker.opacities = marker.opacities.concat([.8, .6, .4, .2, 0]);
      }
    });
  };

  animateMarkers = function() {
    var marker, _i, _len, _ref;
    _ref = [nyMarker, laMarker];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      marker = _ref[_i];
      if (marker.opacities.length > 0) {
        marker.setOpacity(marker.opacities[0]);
        marker.opacities.shift();
      }
    }
    return setTimeout(function() {
      return animateMarkers();
    }, 50);
  };

  init = function() {
    var options,
      _this = this;
    options = {
      center: new google.maps.LatLng(39.8111444, -88.5569364),
      zoom: 4,
      mapTypeControl: false,
      panControl: false,
      zoomControl: false,
      streetViewControl: false
    };
    map = new google.maps.Map(document.getElementById("map"), options);
    nyMarker = addMarkerToMap(40.7127, -74.0059, 1);
    laMarker = addMarkerToMap(34.0500, -118.25, 0);
    map.controls[google.maps.ControlPosition.TOP_RIGHT].push($(getCheckboxDivHtml())[0]);
    animateMarkers();
    return setTimeout(function() {
      addMarkerClickHandler($("#ny"), nyMarker);
      return addMarkerClickHandler($("#la"), laMarker);
    }, 1000);
  };

  $(document).ready(init);

}).call(this);
